public with sharing class NewApexclassForNRU {
    public NewApexclassForNRU() {
        for (Integer i = 0; i < 10; i++) {
            System.debug('This for Nru and we can share this calss to other also');
           
        }
         for (Integer i = 0; i < 6; i++) {
            System.debug('Hello vikas');
            System.debug('Hello vikas');
            System.debug('Hello vikas');
            System.debug('Hello vikas');
            System.debug('Hello vikas');
            System.debug('Hello vikas');

            System.debug('Hello vikas'+i);
         }
          
    }
}